### ISSUE TITLE
Support for 11th gen servers

### ISSUE THREAD

**Issue by Alienwarez123** [Danielv123/serverManager#1]
What would I need to change for this to support the 11th generation servers since the dashboard from your screenshots look pretty cool but I have 2x r610's

**Comment by Danielv123** [comment]
Probably nothing. It uses the IPMI standard, which should be the same. It grabs all the values provided and sorts them based on annotation and units, so even if your system has different names for temp sensors, PSU sensors etc it should turn out the same. Would love if you could test so I can added it to the supported list though :)

**Comment by Alienwarez123** [comment]
Yeah I did try it and it just has this https://cdn.jozefb.co.uk/Iq , this is running in a qnap container and ill try it out on a proper machine to make sure its just not my environment

**Comment by Danielv123** [comment]
Darn. I assume you input the same address and credentials you use to connect to your iDRAC?Do you know which iDRAC version you have?On Dec 9, 2020 00:58, Alienwarez123 <notifications@github.com> wrote:
Yeah I did try it and it just has this https://cdn.jozefb.co.uk/Iq , this is running in a qnap container and ill try it out on a proper machine to make sure its just not my environment

**Comment by Alienwarez123** [comment]
Yeah and 

Device Type | iDRAC6 |  
-- | -- | --
  | Hardware Version | 0.01 |  
  | Firmware Version | 2.85 (Build 04) |  
  | Firmware Updated | Mon Sep 18 16:18:03 2017 |  
  | RAC Time | Wed Dec 9 22:37:40 2020 |  
  | Number of Possible Active Sessions | 5 |  
  | Number of Current Sessions | 0 |  
  | LAN Enabled | Yes |  
  | IPMI Version | 2.0

**Comment by Danielv123** [comment]
Can you try the following commands and send me the output?

    ipmitool -I lanplus -H 192.168.10.170 -U root -P calvin sdr
    ipmitool -I lanplus -H 192.168.10.170 -U root -P calvin sensor

And the following to try maxing out the fans:

    ipmitool -I lanplus -H 192.168.10.169 -U root -P Monster123 raw 0x30 0x30 0x01 0x00
    ipmitool -I lanplus -H 192.168.10.170 -U root -P Monster123 raw 0x30 0x30 0x02 0xff 0x60

If that doesn’t work, try finding similar commands which do similar things and I’ll add support for them. Don’t have any iDRAC6 to test with though. The first two commands show a table of sensor names and values, the 3rd enables static fan control and the 4th sets fan speed to 96%.

**Comment by Alienwarez123** [comment]
root@pterodactylpanel:/home/ptero# ipmitool -I lanplus -H 192.168.1.41 -U root -P calvin sdr
Error: Unable to establish IPMI v2 / RMCP+ session
root@pterodactylpanel:/home/ptero# ping 192.168.1.41
PING 192.168.1.41 (192.168.1.41) 56(84) bytes of data.
64 bytes from 192.168.1.41: icmp_seq=1 ttl=64 time=6.14 ms
64 bytes from 192.168.1.41: icmp_seq=2 ttl=64 time=0.538 ms
64 bytes from 192.168.1.41: icmp_seq=3 ttl=64 time=0.631 ms

**Comment by Alienwarez123** [comment]
sorry this may be my issue since it looks like its to do with a setting on the bios, tomorrow I will see what config it is set to and ill update the bios and idrac to the latest since atm I don't have access to it
https://thebackroomtech.com/wp-content/uploads/idrac-setup.gif

**Comment by Alienwarez123** [comment]
https://cdn.jozefb.co.uk/k9 I have got it working on my r610 but like I had to edit the server.json to do it since I kept on getting this error when editing or adding servers
(node:18) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'resetMetrics' of undefined
    at Socket.<anonymous> (/usr/src/app/src/index.js:197:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 33)

**Comment by Danielv123** [comment]
Fixed that bug, also fixed the precision on the ampmeter counter. Mine doesn't seem to get any more accurate than 1 digit (0.8 amps) so I set it to that. I see you are only getting ambient temperature, thats still not good. If you run the sensor command, do you see any more temperature reading?

**Comment by Alienwarez123** [comment]
Temp             | na         |            | na    | na        | na        | na        | na        | na        | na        
Temp             | na         |            | na    | na        | na        | na        | na        | na        | na        
Temp             | na         |            | na    | na        | na        | na        | na        | na        | na        
Ambient Temp     | na         |            | na    | na        | na        | na        | na        | na        | na        
Temp             | na         |            | na    | na        | na        | na        | na        | na        | na        
Ambient Temp     | na         |            | na    | na        | na        | na        | na        | na        | na        
Ambient Temp     | 11.000     | degrees C  | ok    | na        | 3.000     | 8.000     | 42.000    | 47.000    | na        
Planar Temp      | na         |            | na    | na        | 3.000     | 8.000     | 92.000    | 97.000    | na        
CMOS Battery     | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
VCORE PG         | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
VCORE PG         | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
IOH THERMTRIP    | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
1.5V PG          | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
1.8V PG          | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
3.3V PG          | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
5V PG            | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
0.75VTT PG       | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
PFault Fail Safe | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
HEATSINK PRES    | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
iDRAC6 Ent PRES  | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
USB CABLE PRES   | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
STOR ADAPT PRES  | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
RISER2 PRES      | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
RISER1 PRES      | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
0.75 VTT PG      | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
MEM PG           | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
MEM PG           | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
0.9V PG          | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
VTT PG           | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
VTT PG           | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
1.8 PLL PG       | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
1.8 PLL PG       | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
8.0V PG          | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
1.1V PG          | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
1.0V LOM PG      | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
1.0V AUX PG      | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
1.05V PG         | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
FAN MOD 1A RPM   | 4200.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 2A RPM   | 4200.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 3A RPM   | 4320.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 4A RPM   | 4200.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 5A RPM   | 4200.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 6A RPM   | 4560.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 1B RPM   | 3360.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 2B RPM   | 3360.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 3B RPM   | 3360.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 4B RPM   | 3360.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 5B RPM   | 3360.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
FAN MOD 6B RPM   | 3600.000   | RPM        | ok    | na        | 1920.000  | na        | na        | na        | na        
Presence         | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Presence         | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Presence         | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Presence         | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Presence         | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Status           | 0x0        | discrete   | 0x8080| na        | na        | na        | na        | na        | na        
Status           | 0x0        | discrete   | 0x8080| na        | na        | na        | na        | na        | na        
Status           | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Status           | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Riser Config     | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
OS Watchdog      | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
SEL              | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Intrusion        | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
PS Redundancy    | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Fan Redundancy   | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
CPU Temp Interf  | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Drive            | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Cable SAS A      | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
Cable SAS B      | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
DKM Status       | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
ECC Corr Err     | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
ECC Uncorr Err   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
I/O Channel Chk  | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
PCI Parity Err   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
PCI System Err   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
SBE Log Disabled | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Logging Disabled | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Unknown          | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
CPU Protocol Err | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
CPU Bus PERR     | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
CPU Init Err     | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
CPU Machine Chk  | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Memory Spared    | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Memory Mirrored  | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Memory RAID      | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Memory Added     | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Memory Removed   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Memory Cfg Err   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Mem Redun Gain   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
PCIE Fatal Err   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Chipset Err      | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Err Reg Pointer  | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Mem ECC Warning  | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Mem CRC Err      | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
USB Over-current | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
POST Err         | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Hdwr version err | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Mem Overtemp     | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Mem Fatal SB CRC | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Mem Fatal NB CRC | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
OS Watchdog Time | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Non Fatal PCI Er | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Fatal IO Error   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
MSR Info Log     | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Temp             | na         |            | na    | na        | na        | na        | na        | na        | na        
Temp             | na         |            | na    | na        | na        | na        | na        | na        | na        
Temp             | na         |            | na    | na        | na        | na        | na        | na        | na        
Current          | 0.400      | Amps       | ok    | na        | na        | na        | na        | na        | na        
Current          | 0.280      | Amps       | ok    | na        | na        | na        | na        | na        | na        
Voltage          | 242.000    | Volts      | ok    | na        | na        | na        | na        | na        | na        
Voltage          | 244.000    | Volts      | ok    | na        | na        | na        | na        | na        | na        
System Level     | 175.000    | Watts      | ok    | na        | na        | na        | 917.000   | 966.000   | na        
Power Optimized  | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
ROMB Battery     | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
vFlash           | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na

**Comment by Danielv123** [comment]
Darn, thats a bummer. Can't really use the fan control curve then. Should I add an option of just setting static fan speed?

**Comment by Danielv123** [comment]
What if I added an option to base the fan control curve on power consumption instead? That should align pretty closely to load spikes.

**Comment by Alienwarez123** [comment]
The static fan control does work but not on temperature curve but it works just static  https://cdn.jozefb.co.uk/Ye

**Comment by Danielv123** [comment]
Ah, well I guess that makes sense. It picks the only temperature measurement it can find and applies the curve to that, effectively making it static.
